"""add index to users table

Revision ID: fdc440219952
Revises: b8a6b624a6e6
Create Date: 2024-07-16 15:59:51.399101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc440219952'
down_revision: Union[str, None] = 'b8a6b624a6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'likes', ['user_id', 'tweet_id'])
    op.create_index('ix_user_api_key', 'users', ['api_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_api_key', table_name='users')
    op.drop_constraint(None, 'likes', type_='unique')
    # ### end Alembic commands ###
